### ISSUE TITLE
Resolution too low in XperiaX

### ISSUE THREAD

**Issue by TMavica** [pycage/tidings#47] opened 2017-11-07 15:48 UTC
Aa title

**Comment by TMavica** [comment] 2017-12-01 02:33
no news?

**Comment by pycage** [comment] 2017-12-01 19:21
Not yet. Sorry. :(

**Comment by Ygarr** [comment] 2017-12-06 01:48
Also on Jolla 1 time string partially overlap news header.

**Comment by pycage** [comment] 2017-12-10 10:11
The Xperia X scaling issues should be fixed in latest master.
As for the Jolla 1 time string, I'm not able to reproduce this overlapping.

**Closed by pycage** 2017-12-10 10:11 UTC
